# -*- coding: utf-8 -*-
"""anemia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12G-ncS1zqHKS4-f7RYtXZmPb7tKpipDO
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('anemia.csv')

# Split the dataset into features (X) and target (y)
X = df.drop('Result', axis=1)
y = df['Result']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

# Accuracy score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy*100)

# Classification report
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

# Confusion matrix
matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", matrix)

import joblib

# Save the trained model
joblib.dump(model, 'anemia_model.pkl')

# Remove feature names from the scaler
scaler.feature_names_in_ = None

# Save the scaler
joblib.dump(scaler, 'anemia_scaler.pkl')
